version: 1.2
workflows:
  - name: read_coverage
    subclass: WDL
    description: Compute the read coverage across the genome by bin from an input BAM using mosdepth
    primaryDescriptorPath: /workflow.wdl
    authors:
      - name: Jean Monlong
        email: jmonlong@ucsc.edu
